#!/bin/sh
# lib/config.sh - Read/Write zapret config safely

ZAPRET_CONFIG="/Users/tab/Downloads/Asus-Merlin-Zapret2-GUI/tmp-tests/opt/zapret2/config"

Config_Read() {
    local key="$1"
    local config_file="${2:-$ZAPRET_CONFIG}"
    if [ -f "$config_file" ]; then
        # Run in a subshell to avoid polluting the current environment
        (
            . "$config_file" >/dev/null 2>&1
            eval "echo \"\$$key\""
        )
    fi
}

# Applies a block of variables generated by the GUI, replacing the old block.
# Reads the block from standard input.
Config_Apply_Block() {
    local config_file="${1:-$ZAPRET_CONFIG}"
    local tmp_conf="/Users/tab/Downloads/Asus-Merlin-Zapret2-GUI/tmp-tests/zapret2.conf.tmp"
    
    if [ ! -f "$config_file" ]; then
        touch "$config_file" 2>/dev/null
    fi
    
    # Remove existing GUI settings block and save to temp file
    sed '/^# --- ZAPRET2 GUI SETTINGS START ---$/,/^# --- ZAPRET2 GUI SETTINGS END ---$/d' "$config_file" > "$tmp_conf"
    
    # Append the new block from stdin
    echo "# --- ZAPRET2 GUI SETTINGS START ---" >> "$tmp_conf"
    cat >> "$tmp_conf"
    echo "# --- ZAPRET2 GUI SETTINGS END ---" >> "$tmp_conf"
    
    # Safely overwrite original config
    cat "$tmp_conf" > "$config_file"
    rm -f "$tmp_conf"
}
